services:
  postgres:
    image: postgres
    container_name: postgresdb-container
    volumes:
      - ./database/payments-management/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
      - ./create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    environment:
      POSTGRES_PASSWORD: "usersdb2023"
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-console-container
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks: 
      - postgres-network
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: app-container
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - postgres-network
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    links:
      - "postgres"

networks:
  postgres-network:
    driver: bridge
