export enum CategoryEnum {
  MORADIA = 'MORADIA',
  SUPERMERCADO = 'SUPERMERCADO',
  TV_INTERNET_TELEFONE = 'TV_INTERNET_TELEFONE',
  TRANSPORTE = 'TRANSPORTE',
  LAZER = 'LAZER',
  SAUDE = 'SAUDE',
  EDUCACAO = 'EDUCACAO',
  BARES_RESTAURANTES = 'BARES_RESTAURANTES',
  OUTROS = 'OUTROS',
  FINANCIAMENTOS = 'FINANCIAMENTOS',
}
